### ISSUE TITLE
Add "latest" tag

### ISSUE THREAD

**Issue by nishidayuya** [CircleCI-Public/cimg-shared#82] opened 2023-04-05 12:55 UTC
I want to keep "latest" version support CONTINUOUSLY.

I think following workflow:

1. When CircleCI notifies failure on "latest" tag, set latest succeeded version and show supported version in current commit ID.
2. Fix it! and set "latest" tag again.

**Comment by nishidayuya** [comment] 2023-04-05 13:15
Alias support is implemented in #18 . Perhaps, when releasing new version of Docker image, using alias `=latest` (like Node.js "lts" tag) solves this issue. :eyes:

**Comment by BytesGuy** [comment] 2023-04-26 10:43
Right now we have no plans to introduce a latest tag for any Docker Convenience Images and this is by design.

Hi, thanks for the comments.

We do not use latest/current tags to ensure that jobs based on our images are more deterministic in nature, with minimal changes due to us pushing new tags that switch current to a new major version for example.

This helps minimise the risk of breaking changes occurring when customers have not explicitly updated their configurations.

We provide tags for major.minor versions which point to the latest patch releases as these are generally compatible and do not cause breaking changes.

The Node image is a special case due to how the NodeJS release cycles work. It is not something we are considering for nay other images at this time.

I hope this explanation helps and thanks for the suggestions! I will close this issue out, but please feel free to re-open it with any additional comments.

**Closed by BytesGuy** 2023-04-26 10:43 UTC
